kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  name: openshiftfilecopyservice
  generation: 1
  namespace: amilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshiftfilecopyservice
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: openshiftfilecopyservice
    spec:
      volumes:
        - name: zalenium-videos
          persistentVolumeClaim:
            claimName: zalenium-video
      containers:
        - name: openshiftfilecopyservice
          image: >-
            openshiftfilecopyservice:1.0.0
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 1Gi
          volumeMounts:
            - name: zalenium-videos
              mountPath: /home/seluser/videos
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
